on:
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Pre-print
    steps:
      - uses: actions/checkout@v2
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k joss/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper/
